apiVersion: apps/v1
kind: Deployment
metadata:
  name: o11y-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: o11y-workshop
  template:
    metadata:
      labels:
        app: o11y-workshop
    spec:
      containers:
        - name: o11y-workshop
          image: docker.io/devx/test:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: o11y-workshop-service
spec:
  type: LoadBalancer
  selector:
    app: o11y-workshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
