apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: logz-io-o11y-workshop
  region: eu-central-1
  version: "1.27"

managedNodeGroups:
  - name: workers
    labels: { role: workers }
    instanceType: t3a.medium
    desiredCapacity: 4
    volumeSize: 80
    privateNetworking: true
    tags:
      Environment: workshop
      Owner: workshop-attendee